```{r}
plot(sleep$ClassesMissed,sleep$CognitionZscore)
plot(sleep$PoorSleepQuality,sleep$CognitionZscore)
```

```{r}
plot(sleep$WeekdayBed,sleep$CognitionZscore)

lm1<-lm(sleep$CognitionZscore~sleep$WeekdayBed)
abline(lm1,col="red")
summary(lm1)
summary(sleep$WeekdayBed)
```

```{r}
plot(sleep$WeekdayRise,sleep$CognitionZscore)

lm1<-lm(sleep$CognitionZscore~sleep$WeekdayRise)
abline(lm1,col="red")
summary(lm1)
summary(sleep$WeekdayRise)
```

```{r}
plot(sleep$LarkOwl,sleep$CognitionZscore)

lm1<-lm(sleep$CognitionZscore~sleep$LarkOwl)
abline(lm1,col="red")
summary(lm1)
summary(sleep$LarkOwl)
```

```{r}
plot(sleep$WeekdaySleep,sleep$CognitionZscore)

lm1<-lm(sleep$CognitionZscore~sleep$WeekdaySleep)
abline(lm1,col="red")
summary(lm1)
summary(sleep$WeekdaySleep)
```

```{r}
plot(sleep$WeekendBed,sleep$CognitionZscore)

lm1<-lm(sleep$CognitionZscore~sleep$WeekendBed)
abline(lm1,col="red")
summary(lm1)
summary(sleep$WeekendBed)
```

```{r}
plot(sleep$WeekendSleep,sleep$CognitionZscore)

lm1<-lm(sleep$CognitionZscore~sleep$WeekendSleep)
abline(lm1,col="red")
summary(lm1)
summary(sleep$WeekendSleep)
```

```{r}
plot(sleep$AverageSleep,sleep$GPA)

lm1<-lm(sleep$GPA~sleep$AverageSleep)
abline(lm1,col="red")
summary(lm1)
summary(sleep$AverageSleep)
```

```{r}
plot(sleep$AllNighter,sleep$CognitionZscore)

lm1<-lm(sleep$CognitionZscore~sleep$AllNighter)
abline(lm1,col="red")
summary(lm1)
summary(sleep$AllNighter)
```

```{r}
plot(sleep$DepressionScore,sleep$CognitionZscore)

lm1<-lm(sleep$CognitionZscore~sleep$DepressionScore)
abline(lm1,col="red")
summary(lm1)
summary(sleep$DepressionScore)
```

```{r}
plot(sleep$AnxietyScore,sleep$CognitionZscore)

lm1<-lm(sleep$CognitionZscore~sleep$AnxietyScore)
abline(lm1,col="red")
summary(lm1)
summary(sleep$AnxietyScore)
```

```{r}
plot(sleep$StressScore,sleep$CognitionZscore)

lm1<-lm(sleep$CognitionZscore~sleep$StressScore)
abline(lm1,col="red")
summary(lm1)
summary(sleep$StressScore)
```

```{r}
plot(sleep$Stress,sleep$CognitionZscore)

lm1<-lm(sleep$CognitionZscore~sleep$Stress)
abline(lm1,col="red")
summary(lm1)
summary(sleep$Stress)
```